captureDirectory: captures # Where you want the captures to be saved to
completeDirectory: complete # Where you want the "finalized" captures to be moved to as soon as model stops streaming
modelScanInterval: 60 # In seconds, how often showuptv-node checks for newly-online models
debug: true
rtmpDebug: false
minFileSizeMb: 5
models:
  - TlustaDupcia
  - ZemraOla
  - katematias77
  - S_UZANKAA
  - _Darya
  - DollM
  - Hasitka
  - PrettyBaby
  - Promyczek_
  - Channel_5
  - warszawskakocica
  - Mini_Mouse
  - Icespage
  - lynncamgrl
  - wampstar
  - blond_lila
  - evilglow
  - Serduszko18
  - Tequila3
  - Make_you_mine
  - Slodka_WrednaDiablica
  - divine_eve
  - Asinna
  - obsesion
  - annabellee123
  - ToxicAngel-FromHell
  - Landrynka88
  - Hot_Oliwia
  - AliceLayla
  - Karinchik_
  - Sandracrazy
  - Kesja_
  - Liliankax
  - delevinannaa
  - masha2005
  - Squirtujaca_kotka91
  - Himeko
  - hotkatherine
  - inaccessibleTwo
  - Butterfly_
  - PrettyKilla
  - VolorFlex
  - Sweet00
  - karolinaem
  - gwiazda
  - Krysztalowa_dama
  - BodyLina
  - Sexy_Vika
  - onaciekawajego
  - MalwinaFoot
  - _Borderline__
  - Mg_hart
  - Little_girl
  - Miss_Kriss
  - Daisy1987
  - namietna_kociczkaaa
  - DOMINA-MARTA32
  - ElissaBerry
  - GosiaSamosia27
  - Wtajemniczeni_x2
  - xLilia
  - Akuma_Amai__
  - SENSI_PARIS
  - DANGRO996
  - IIIlI_m_a_d_d_i_s_o_n_Ill
  - Blue_Lady_tatoo  - Cream_sheese
  - evilglow
  - DziennikErotomanki
  - suuka_20
  - MissDominique313
  - obsesion
  - xmeerceedesx
  - Akuma_Amai__
  - Landrynka88
  - LiviaLarosa
  - Sexy_Nikol
  - delevinannaa
  - Icespage
  - Natalia-97
  - xNaughtyxgirlx
  - divine_eve
  - Liliankax
  - twojakotkaa
  - Self-control
  - Kochana_Milenka
  - marinapragnie6969
  - MILFdojebania
  - Sandracrazy
  - Karinchik_
  - Kesja_
  - 0livia22
  - SpragnionaRozkoszyy
  - -Inu97-
  - karolcia_96
  - KristinaXX
  - Robienadgodziny
  - VolorFlex
  - xHoney
  - paranienormalni
  - myszkaBisex
  - Mg_hart
  - betisu85
  - _XIXIXI_
  - JamaMajka
  - gwiazda
  - Suzi_Su
  - zuzia48
  - idealnadupka
  - xLilia
  - namietna_kociczkaaa
  - Domina_Laura
  - niesmiala__blondi
  - DOMINA-MARTA32
  - _404girl_not_found
